name: Workflow for Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run-tests:
        description: 'TestInput'
        required: false
        default: 'Some str value'
        type: string

jobs:
    fake_flow:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Fake step
          run: echo "This is a fake workflow for testing purposes."